### ISSUE TITLE
Downloading the created clang-format does not contain all selected options

### ISSUE THREAD

**Issue by chill-nemesis** [Wirena/clang-format-configurator-v2#21]
# Info
Configurator was set to `16.0.1`
Browser is Vivaldi 6.0.2979.18 stable

# Issue
After modifying some of the options and downloading the .clang-format file, some of the options are missing.

I first assumed that it were only some default values, but after comparing against the default clang-format documentation, that does not seem to be the case.
It seems to be always the same options that are missing though.
One example for me was `AlignOperands: Align` which I set but was missing in the downloaded file.

I have attached a section of my desired config as it is set in your configurator: 
![image](https://github.com/Wirena/clang-format-configurator-v2/assets/12547922/6ddcb22d-f4d2-44d5-96db-21248772f02f)

and here is the corresponding section from the generated clang-format file:
```
BraceWrapping:
  AfterClass: false
  BeforeLambdaBody: true
  IndentBraces: false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false
```
