### ISSUE TITLE
Formatting is not idempotent with Cpp11BracedListStyle

### ISSUE THREAD

**Issue by detly** [Wirena/clang-format-configurator-v2#44]
To reproduce:

1. Unselect _Autoformat on changes_ (I don't know if this is related, it just makes it easier to separate the steps).
2. Paste in this code:

    ```c
    #include <stdbool.h>
    #include <stdlib.h>
    
    typedef struct {
        int kind;
    
        struct {
            bool is_low;
            double level;
        } power;
    } event_t;
    
    event_t* do_thing(bool flag, double voltage)
    {
        if (flag) {
            event_t* power_event = malloc(sizeof *power_event);
    
            *power_event = (event_t) {
                .kind = 1,
                .power = {
                    .is_low = true,
                    .level = voltage,
                },
            };
    
            return power_event;
        }
    
        return NULL;
    }
    ```

3. Click _Config File_ and replace the entire contents with:

    ```yaml
    BasedOnStyle: WebKit
    Language: Cpp
    AlignAfterOpenBracket: BlockIndent
    AlignOperands: AlignAfterOperator
    BinPackArguments: false
    BinPackParameters: false
    BreakBeforeBinaryOperators: NonAssignment
    Cpp11BracedListStyle: true
    ```

4. Click _Load Config_.
5. Click _Format_. Note that the brace after `.power =` gets put on a new line and indented.
6. Click _Config File_ and replace the entire contents with the same config **except** the `Cpp11BracedListStyle` line. Click _Load Config_ and _Format_.
7. Note that the `.power = {` brace is now back on the same line.
8. Click _Config File_ and replace the entire contents with the same config as step 3, **including** the `Cpp11BracedListStyle` line. Click _Load Config_ and _Format_.
9. The `.power = {` brace remains on the same line.

I would except that with the same source and the same config, steps 8 and 3 should produce the same results.

This happens with `clang-format` _Version_ 16.0.6 and 17.0.6 selected.

Browser is Firefox 124.0 (64-bit) installed via Snap on Ubuntu 23.10.
