### ISSUE TITLE
AlignConsecutiveAssignments allows named option groups in clang-format 18

### ISSUE THREAD

**Issue by detly** [Wirena/clang-format-configurator-v2#52]
In clang-format 18, [`AlignConsecutiveAssignments`](https://releases.llvm.org/18.1.0/tools/clang/docs/ClangFormatStyleOptions.html#alignconsecutiveassignments) allows both a nested dict or an enumerated type, with values:

- `None`
- `Consecutive`
- `AcrossEmptyLines`
- `AcrossComments`
- `AcrossEmptyLinesAndComments`

Two related issues show with the current site:

1. These options are not selectable with the UI. But they can be achieved just by setting the individual options that correspond to each group.
2. Uploading a configuration file containing these grouped settings results in an error:

   > ## Something went wrong:
   >     Clang-format returned non zero code
   >     <command-line>:17:7: error: unknown key '9'
   >        "9": 'v',
   >           ^~~
   >     Error parsing -style: Invalid argument

Clicking on "Config File" again shows that `AlignConsecutiveAssignments` has been changed into:

```yml
AlignConsecutiveAssignments:
  "0": C
  "1": o
  "2": n
  "3": s
  "4": e
  "5": c
  "6": u
  "7": t
  "8": i
  "9": v
  "10": e
  Enabled: false
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: false
  AlignFunctionPointers: false
  PadOperators: true
```

**Comment by detly** [comment]
Oh, it's the same for `AlignConsecutiveDeclarations` and `AlignConsecutiveMacros`.

**Comment by Wirena** [comment]
@detly thanks for your bug report!
Yeah, legacy values for all `AlignConsecutive*` options are not supported by this configurator, it's mentioned in the readme file.

I've made this popup error message to notify users about this limitation, but it looks like this message does not appear when `BasedOnStyle` option is set, can confirm that. Could you please provide original config file used in your example, just in case? 

![image](https://github.com/user-attachments/assets/e55f4a78-e4a0-400d-8f39-974c263ad5a1)

I'll fix the error message not appearing.
As for support for these legacy values, I doubt I can add them to the main UI page, there's too much shitcode and architectural design flaws. 
Finding which combination of nested values corresponds to legacy value and offering user to convert it in the Config File UI page looks more realistic solution to me

**Comment by detly** [comment]
> Yeah, legacy values for all AlignConsecutive* options are not supported by this configurator, it's mentioned in the readme file.

Ah sorry, I thought they were _new_ values, not legacy ones. I might change those in my own project then. You can disregard that part of it then.

However:

> but it looks like this message does not appear when BasedOnStyle option is set

Indeed, I have `WebKit` for that:

```yml
BasedOnStyle: WebKit
Language: Cpp

ColumnLimit: 88

SortIncludes: CaseInsensitive

AlignAfterOpenBracket: BlockIndent

BreakBeforeBraces: Custom
BraceWrapping:
    AfterCaseLabel: true
    AfterControlStatement: true
    AfterEnum: true
    AfterFunction: true
    AfterStruct: true
    AfterUnion: true
    BeforeElse: true
    BeforeWhile: true

AlignConsecutiveAssignments: Consecutive
AlignConsecutiveDeclarations: Consecutive
AlignConsecutiveMacros: Consecutive
AlignEscapedNewlines: Left
AllowAllArgumentsOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Empty
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: NonAssignment
IndentCaseLabels: true
IndentPPDirectives: BeforeHash
InsertBraces: true
KeepEmptyLinesAtEOF: false
KeepEmptyLinesAtTheStartOfBlocks: false
PointerAlignment: Middle
QualifierAlignment: Left
ReflowComments: true
RemoveSemicolon: true
SpaceAfterCStyleCast: true

PenaltyBreakAssignment: 0
PenaltyReturnTypeOnItsOwnLine: 0
```
